### ISSUE TITLE
Error: Type name Gjs_Current_screen_only_for_Alternative_Tab_bourcereau_fr_extension_CurrentMonitorWindowSwitcherPopup is already registered

### ISSUE THREAD

**Issue by Dominik1123** [mmai/Current_screen_only_on_window_switcher#8] opened 2021-01-27 20:57 UTC
I'm receiving the following error (it seems after locking / unlocking the screen, but I'm not 100% sure that's the reason):

![image](https://user-images.githubusercontent.com/15989985/106052466-e32dad00-60e9-11eb-8f15-f7326076f7f1.png)

The application stops then working. Is this a bug or can I work around this somehow?

This is the output from `sudo journalctl /usr/bin/gnome-shell`:

```
JS ERROR: Extension Current_screen_only_for_Alternate_Tab@bourcereau.fr: Error: Type name Gjs_Current_screen_only_for_Alternate_Tab_bourcer>
                                        _init/GObject.Object._classInit@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:448:27
                                        registerClass@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:94:22
                                        enable_3_32@/home/dominik/.local/share/gnome-shell/extensions/Current_screen_only_for_Alternate_Tab@bourcereau.fr/extension.js:37:40
                                        enable@/home/dominik/.local/share/gnome-shell/extensions/Current_screen_only_for_Alternate_Tab@bourcereau.fr/extension.js:13:5
                                        _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:167:32
                                        _enableAllExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:612:22
                                        _enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:611:37
                                        _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:639:18
                                        _emit@resource:///org/gnome/gjs/modules/core/_signals.js:133:47
                                        _sync@resource:///org/gnome/shell/ui/sessionMode.js:198:14
                                        popMode@resource:///org/gnome/shell/ui/sessionMode.js:166:14
                                        _continueDeactivate@resource:///org/gnome/shell/ui/screenShield.js:502:30
                                        deactivate/<@resource:///org/gnome/shell/ui/screenShield.js:493:44
                                        finish@resource:///org/gnome/shell/gdm/authPrompt.js:523:13
                                        finish@resource:///org/gnome/shell/ui/unlockDialog.js:867:26
                                        deactivate@resource:///org/gnome/shell/ui/screenShield.js:493:26
                                        ScreenShield/</<@resource:///org/gnome/shell/ui/screenShield.js:110:57
                                        _emit@resource:///org/gnome/gjs/modules/core/_signals.js:133:47
                                        _convertToNativeSignal@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:169:19
```

**Comment by mmai** [comment] 2021-02-05 08:23
Duplicate of #6 
I've merged a pull request fixing this bug. It's now pending for review https://extensions.gnome.org/review/22144

**Closed as completed by mmai** 2021-02-05 08:23 UTC
